experiments:
  aoa_spanish_without_ft_selected_words_AoA_Spanish_fromAoE_10k_test:
    dataset_path: "selected_words_AoA_Spanish_fromAoE_10k_test.xlsx"
    dataset_column: "Word"
    prompt_path: "spanish_v0.txt"
    model_name: "gpt-4o-mini-2024-07-18"
  
  aoa_spanish_ft_spanish_selected_words_AoA_Spanish_fromAoE_10k_test:
    dataset_path: "selected_words_AoA_Spanish_fromAoE_10k_test.xlsx"
    dataset_column: "Word"
    prompt_path: "spanish_v0.txt"
    model_name: "ft:gpt-4o-mini-2024-07-18:ging-upm:aoa-spanish-ft-fromaoe-cross-2:BxgI7Nbj"
  



finetuning:
  aoa_spanish_ft_fromAoE_cross:
    # create finetuning dataset:
    ft_dataset_path: "selected_words_AoA_Spanish_fromAoE_10k.xlsx"
    train_split_percentage: 0.291686923
    random_state: 42
    answer_column: "mean_adj"
    prompt_path: "spanish_v0.txt"
    prompt_assistant_path: "spanish_v0_ft_assistant.txt" #optional in other experiments
    # execute finetuning:
    dataset_finetune_name: "selected_words_AoA_Spanish_fromAoE_10k.jsonl"
    model_name: "gpt-4o-mini-2024-07-18"
    especial_suffix: "aoa_spanish-ft-fromAoE-cross_2"
    # output ft:gpt-4o-mini-2024-07-18:ging-upm:aoa-spanish-ft-fromaoe-cross-2:BxgI7Nbj



