experiments:
  
  iconicity_english_base_prompt_gpt-4o:
    dataset_path: "iconicity_ratings_english.xlsx"
    dataset_column: "word"
    prompt_path: "english_base_prompt.txt"
    model_name: "gpt-4o-mini-2024-07-18"
    company: "OpenAI"

finetuning:

  ft_iconicity_english_base_prompt_gpt-4o_glas_mrc_mean_gpt-4o:
    # create finetuning dataset:
    ft_dataset_path: "train_iconicity_ratings_english.xlsx"
    train_split_percentage: 1
    random_state: 42
    answer_column: "iconicity_english_glas_mrc_mean"
    prompt_path: "english_base_prompt.txt"
    # prompt_assistant_path: ""
    # execute finetuning:
    dataset_finetune_name: "ft_iconicity_english_base_prompt_gpt-4o_glas_mrc_mean_gpt-4o.jsonl"
    model_name: "gpt-4o-mini-2024-07-18"
    especial_suffix: "iconicity_english_gpt-4o_glas_mrc_mean_gpt-4o"
    company: "OpenAI"
